### ISSUE TITLE
where is the file: personalized-dialog-dataset/modified-candidates.txt

### ISSUE THREAD

**Issue by SeekPoint** [chaitjo/personalized-dialog#1]
since I can not access dropbox, so I download the tar.gz and untar it manually

**Comment by SeekPoint** [comment]
mldl@mldlUB1604:\~/ub16_prj/personalized-dialog/MemN2N$ python single_dialog.py --train True --task_id 1
.........
2017-07-31 21:35:23.929671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0)
Started Task: 1
Traceback (most recent call last):
  File "single_dialog.py", line 229, in <module>
    chatbot=chatBot(FLAGS.data_dir,model_dir,FLAGS.task_id,OOV=FLAGS.OOV,isInteractive=FLAGS.interactive,batch_size=FLAGS.batch_size,memory_size=FLAGS.memory_size,save_vocab=FLAGS.save_vocab,load_vocab=FLAGS.load_vocab)
  File "single_dialog.py", line 58, in __init__
    candidates,self.candid2indx = load_candidates(self.data_dir, self.task_id)
  File "/home/mldl/ub16_prj/personalized-dialog/MemN2N/data_utils.py", line 17, in load_candidates
    with open(os.path.join(data_dir,candidates_f)) as f:
IOError: [Errno 2] No such file or directory: '../data/personalized-dialog-dataset/modified-candidates.txt'
mldl@mldlUB1604:\~/ub16_prj/personalized-dialog/MemN2N$ 
mldl@mldlUB1604:\~/ub16_prj/personalized-dialog/MemN2N$ 
mldl@mldlUB1604:\~/ub16_prj/personalized-dialog/MemN2N$ ll ../data/personalized-dialog-dataset/
total 5816
drwxr-xr-x 5 mldl mldl    4096 6月  26 15:38 ./
drwxrwxr-x 3 mldl mldl    4096 7月  31 21:34 ../
drwxr-xr-x 2 mldl mldl    4096 6月  16 04:04 full/
-rw-r--r-- 1 mldl mldl   19906 6月  16 02:00 LICENSE
-rw-r--r-- 1 mldl mldl 3728063 6月  16 04:01 personalized-dialog-candidates.txt
-rw-r--r-- 1 mldl mldl 2175310 6月  16 04:01 personalized-dialog-kb-all.txt
-rw-r--r-- 1 mldl mldl    2998 6月  26 15:38 README.md
drwxr-xr-x 2 mldl mldl    4096 6月  16 04:04 small/
drwxr-xr-x 8 mldl mldl    4096 6月  21 21:18 split-by-profile/
mldl@mldlUB1604:~/ub16_prj/personalized-dialog/MemN2N$

**Comment by chaitjo** [comment]
Hello! Thanks for the interest. I could  not understand your question properly. Do you need help with downloading the data?

**Comment by chaitjo** [comment]
Hi @loveJasmine thanks for the interest! I believe your issue was caused by a problem in the paths to specific files. I have made a fix in the latest commit. Thank you for pointing it out!

**Comment by SeekPoint** [comment]
so on which version of  tensorflow it should run ?

**Comment by chaitjo** [comment]
Both the Memory Network and Supervised Embedding model are running on tensorflow 0.12.1. I plan to update to the latest api as soon as possible. Thank you for pointing this out as well, I shall add it to the READMEs.

Additionally, if you are interested in using an unmodified Memory Network model with our dataset, you can also use Facebook AI's [ParlAI framework](http://parl.ai/). All data is downloadable through their system.

**Comment by SeekPoint** [comment]
@chaitjo  thanks your quick response.

would you also include the operation of ParAI in the update readme? thanks

**Comment by chaitjo** [comment]
Yes, I can include a step-by-step guide to running this on ParlAI. Till then, I recommend going through the tutorials included in ParlAI's github repository to get a general understanding. Using our data is simple from thereon.

I think running the following command in ParlAI will run their model on the dataset (after downloading all the data)-
```
$ cd <path-to-ParlAI>/examples
$ python memnn_luatorch_cpu/full_task_train.py -t personalized_dialog:FullTask:<task_id>
```
If you want to run on the small set, replace 'FullTask' with 'SmallTask'. Replace <task_id> with the id of the required task. 

In general, to utilize the dataset anywhere within ParlAI, use the flag `-t personalized_dialog:FullTask:<task_id>`.
