### ISSUE TITLE
Performance issues in the definition of _inference, MemN2N-split-memory/memn2n/memn2n_dialog.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [chaitjo/personalized-dialog#12]
Hello, I found a performance issue in the definition of _inference, MemN2N-split-memory/memn2n/memn2n_dialog.py, [`tf.nn.embedding_lookup(self.A, stories)`](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N-split-memory/memn2n/memn2n_dialog.py#L157) will be created repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop.

The same issues exist in:

- [`tf.nn.embedding_lookup(self.A, profile)` in line 158](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N-split-memory/memn2n/memn2n_dialog.py#L158);
- [`tf.reduce_sum(m_emb, 2)` in line 160 and 161](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N-split-memory/memn2n/memn2n_dialog.py#L160);
- [`tf.transpose(m, [0, 2, 1])` in line 183](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N-split-memory/memn2n/memn2n_dialog.py#L183);
- [`tf.transpose(m_profile, [0, 2, 1])` in line 184](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N-split-memory/memn2n/memn2n_dialog.py#L184);
- [`tf.nn.embedding_lookup(self.A, stories)` in line 154](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N/memn2n/memn2n_dialog.py#L154);
- [`tf.reduce_sum(m_emb, 2)` in line 155](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N/memn2n/memn2n_dialog.py#L155);
- [`tf.transpose(m, [0, 2, 1])`](https://github.com/chaitjo/personalized-dialog/blob/4f94e3dc1376e4e6aa1e5be3ec08b9f56871c98e/MemN2N/memn2n/memn2n_dialog.py#L169);

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by chaitjo** [comment]
Sorry, this codebase is not being maintained.
