### ISSUE TITLE
what's the different between  'MemN2N' and 'MemN2N-modified', 

### ISSUE THREAD

**Issue by SeekPoint** [chaitjo/personalized-dialog#2]
if I want work on on of them for study and improvement purpose, on which one you suggest based?

**Comment by chaitjo** [comment]
Hey! Thanks for the interest. The MemN2N model is the one described in FAIR's bAbI Dialog Tasks paper as well as in our paper on arXiv. The MemN2N-modified model is a new model we are currently working on and intend to add to the paper.

The code for the modified model is still not completely finalized, but a rough idea is to split the model's memory into two- one for the profile attributes and one for the conversation history. The model then combines the outputs over these two memories to produce the final output.

You can use either, as the code has not changed a lot between the two models.

**Comment by SeekPoint** [comment]
great! I will check both of them

**Comment by chaitjo** [comment]
The modified model, called the *split memory* architecture, has been added in an updated version of the paper on arXiv: https://arxiv.org/abs/1706.07503

**Comment by SeekPoint** [comment]
great job
