### ISSUE TITLE
path issue on supervised-embedding 

### ISSUE THREAD

**Issue by SeekPoint** [chaitjo/personalized-dialog#3]
bin/train_all.sh
bin/task1.sh: line 12: data/candidates.tsv: No such file or directory
bin/utils.sh: line 12: data/train-task-1.tsv: No such file or directory
bin/utils.sh: line 13: data/dev-task-1.tsv: No such file or directory
bin/utils.sh: line 14: data/test-task-1.tsv: No such file or directory
bin/utils.sh: line 15: data/dev-task-1-500.tsv: No such file or directory
bin/utils.sh: line 16: data/vocab-task-1.tsv: No such file or directory
cat: data/train-task-1.tsv: No such file or directory
cat: data/dev-task-1.tsv: No such file or directory
cat: data/test-task-1.tsv: No such file or directory
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    vocab = load_vocab(args.vocab)
  File "//personalized-dialog/supervised-embedding/make_tensor.py", line 36, in load_vocab
    with open(vocab_filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'data/vocab-task-1.tsv'
bin/task2.sh: line 12: data/candidates.tsv: No such file or directory
bin/utils.sh: line 12: data/train-task-2.tsv: No such file or directory
bin/utils.sh: line 13: data/dev-task-2.tsv: No such file or directory
bin/utils.sh: line 14: data/test-task-2.tsv: No such file or directory
bin/utils.sh: line 15: data/dev-task-2-500.tsv: No such file or directory
bin/utils.sh: line 16: data/vocab-task-2.tsv: No such file or directory
cat: data/train-task-2.tsv: No such file or directory
cat: data/dev-task-2.tsv: No such file or directory
cat: data/test-task-2.tsv: No such file or directory

**Comment by chaitjo** [comment]
The supervised embedding model creates .tsv files for the data before running. Make sure that these files have been created prior to training.

Maybe the paths to the data files in the `task$.sh` files have to be changed to work.
